{{ range $namespace := .Values.namespaces }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ . }}
{{- with $.Values.labels }}
  labels:
    {{ toYaml . | nindent 4 }}
{{- end }}
{{- with $.Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
    
{{- end -}}