ingressClass: nginx
tcpExternalConfig: "true"
controller:
  config:
    hsts-include-subdomains: "false"
    server-name-hash-bucket-size: "256"
    enable-vts-status: "true"
    use-http2: "false"
    ssl-ciphers: "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4"
    ssl-protocols: "TLSv1.3 TLSv1.2"
    server-tokens: "false"
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
  publishService:
    enabled: true
  replicaCount: 3
  minAvailable: 2
  scope:
    enabled: false
  stats:
    enabled: true
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
defaultBackend:
  minAvailable: 1
  replicaCount: 1
  resources:
    requests:
      cpu: 5m
      memory: 5Mi
rbac:
  create: true
serviceAccount:
  create: true